# Generated by Django 4.0.4 on 2022-05-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfrench',
            old_name='vocal_ref',
            new_name='ref',
        ),
    ]
