# Generated by Django 4.0.4 on 2022-05-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_vocal_ref_textfrench_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textarabic',
            name='audio',
            field=models.FileField(null=True, upload_to='media/audio'),
        ),
    ]
