# Generated by Django 4.0.4 on 2022-05-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_textarabic_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textarabic',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio'),
        ),
    ]
