# Generated by Django 4.0.4 on 2022-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_textarabic_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfrench',
            name='ref',
        ),
        migrations.AddField(
            model_name='textfrench',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio'),
        ),
        migrations.AddField(
            model_name='textfrench',
            name='normalization',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
