# Generated by Django 4.0.4 on 2022-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_textfrench_ref_textfrench_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=600)),
                ('audio', models.FileField(blank=True, null=True, upload_to='media/audio')),
                ('lang', models.BooleanField(default='ar')),
                ('normalization', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TextArabic',
        ),
        migrations.DeleteModel(
            name='TextFrench',
        ),
    ]
