# Generated by Django 4.0.4 on 2022-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_text_delete_textarabic_delete_textfrench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('ar', 'ar'), ('fr', 'fr')], max_length=50),
        ),
    ]
